name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: rahulacrdevops.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t rahulacrdevops.azurecr.io/cicd:${{ github.sha }}
        docker push rahulacrdevops.azurecr.io/cicd:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'rahuldevops'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'rahulacrdevops.azurecr.io/cicd:${{ github.sha }}'
